### PR TITLE
brand-model

### PR DESCRIPTION
**Pull request by commenthol**
This PR enables "brand-model" parsing according to the [Specification](https://github.com/ua-parser/uap-core/blob/master/docs/specification.md).

Note: Tests will **NOT** pass unless https://github.com/ua-parser/uap-core/pull/10 is merged.

### CODE REVIEW

**Comment by commenthol** [comment]
pong

**Comment by lstrojny** [comment]
Looks still good, can you update again against master, then we are finally done

**Comment by commenthol** [comment]
is rebased

**Comment by commenthol** [comment]
tests have all passed. Can you please merge? Thx.

**Comment by lstrojny** [comment]
Thank you again!

**Pull request merged**
